server:
  port: 8082

spring:
  application:
    name: content-service
  
  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5434}/${POSTGRES_DB:social_db}
    username: ${POSTGRES_USER:ibou}
    password: ${POSTGRES_PASSWORD:iboudia}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect

  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      properties:
        spring.json.add.type.headers: false

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8081

eureka:
  client:
    service-url:
      default-zone: http://localhost:8761/eureka/
