server:
  port: 8082

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/content_db
    username: social_user
    password: changeme_postgres
  jpa:
    hibernate:
      ddl-auto: create
  kafka:
    bootstrap-servers: localhost:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      properties:
        spring.json.add.type.headers: false
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8081

media:
  path: /api/v1/media

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/