spring:
  application:
    name: gateway-service

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8081

  cloud:
    gateway:
      server:
        webflux:
          discovery:
            locator:
              enabled: true
          routes:
            - id: notification-service
              uri: lb://NOTIFICATION-SERVICE
              predicates:
                - Path=/api/v1/notifications/**
              filters:
                - StripPrefix=2
          default-filters:
            - TokenRelay

eureka:
  client:
    service-url:
      default-zone: http://localhost:8761/eureka/

server:
  port: 8080