server:
  port: 8083

spring:
  application:
    name: social-service

  datasource:
    url: jdbc:postgresql://localhost:5432/social_db
    username: social_user
    password: changeme_postgres
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect

  kafka:
    bootstrap-servers: localhost:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      properties:
        spring.json.trusted.packages: "sn.edu.ept.postgram.shared.events"
    consumer:
      group-id: social-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: "sn.edu.ept.postgram.shared.events"

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8081

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka