server:
  port: 8083   # ou laisse vide si tu utilises config-server

spring:
  application:
    name: social

  datasource:
    url: jdbc:postgresql://localhost:5432/follow
    username: amnatah
    password: 1234
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect

  kafka:
    bootstrap-servers: localhost:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer


#eureka:
#  client:
#    service-url:
#      defaultZone: http://localhost:8761/eureka