spring:
  application:
    name: auth

  jpa:
    hibernate:
      ddl-auto: update
  sql:
    init:
      mode: always
      schema-locations: classpath:sql/oauth2-schema.sql

  datasource:
    url: jdbc:postgresql://localhost:5432/oidc
    username: ${POSTGRES_USER:social_user}
    password: ${POSTGRES_PASSWORD:changeme_postgres}
    driver-class-name: org.postgresql.Driver

server:
  port: 8081

logging:
  level:
    org.springframework.security: TRACE

app:
  oauth2:
    redirect-uri:
      web: http://localhost:4200/oauth/callback
      mobile: socialapp://callback
  security:
    admin:
      username: ${ADMIN_USERNAME:admin}
      password: ${ADMIN_PASSWORD:admin}
      email: ${ADMIN_EMAIL:admin@example.com}