server:
  port: 8086

spring:
  application:
    name: messaging-service
  profiles:
    active: dev

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${AUTHORIZATION_SERVER}

  datasource:
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    url: ${MESSAGING_DB_URL}

  jpa:
    hibernate:
      ddl-auto: update

eureka:
  client:
    service-url:
      default-zone: http://${EUREKA_SERVER}:${EUREKA_PORT}/eureka/