spring:
  application:
    name: messaging-service

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8081

  datasource:
    username: social_user
    password: changeme_postgres
    url: jdbc:postgresql://localhost:5432/messaging_db

  jpa:
    hibernate:
      ddl-auto: update

  kafka:
    bootstrap-servers: localhost:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      properties:
        spring.json.add.type.headers: false

eureka:
  client:
    service-url:
      default-zone: http://localhost:8761/eureka/