server:
  port: 8087

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/media_db
    username: social_user
    password: changeme_postgres
  jpa:
    hibernate:
      ddl-auto: create
  servlet:
    multipart:
      enabled: true
      max-file-size: 50MB
      max-request-size: 50MB
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8081

app:
  minio:
    endpoint: http://localhost:9000
    access-key: minioadmin
    secret-key: changeme_minio
    buckets:
      avatars: avatars
      posts: posts
  file-size:
    avatar: 5242880 # 5MB
    media: 52428800 # 50MB

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/