server:
  port: 8084

spring:
  application:
    name: feed-service
  data:
    redis:
      host: localhost
      port: 6379
      password: changeme_redis
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: feed-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: "sn.edu.ept.postgram.shared.events"
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8081

feed:
  max-size: 500
  default-page-size: 20

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/